version: "3.1"

services:
  kafkaserver:
    image: "wurstmeister/kafka:2.12-2.1.0"
    container_name: kafka
    hostname: kafkaserver
    networks:
      - kafkanet
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_LISTENERS: "KAFKA://0.0.0.0:9092"
      KAFKA_ADVERTISED_LISTENERS: "KAFKA://localhost:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: KAFKA:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: KAFKA
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    networks:
      - kafkanet
    ports:
      - 2181
#  kafka_manager:
#    image: "mzagar/kafka-manager-docker:1.3.3.4"
#    container_name: kafkamanager
#    networks:
#      - kafkanet
#    ports:
#      - 9000:9000
#    links:
#      - kafkaserver
#    environment:
#      ZK_HOSTS: "kafkaserver:2181"

networks:
  kafkanet:
    driver: bridge

